server:
  port: 8080
  
spring:
    application:
      name: itms
    redis:
          database: 0
          host: 118.31.59.56
          password: ghj#GKuLister
          port: 6379
    freemarker:
      request-context-attribute: req  #req访问request
      suffix: .ftl  #后缀名
      content-type: text/html
      enabled: true
      cache: false #缓存配置
      template-loader-path: classpath:/templates/ #模板加载路径 按需配置
      charset: UTF-8 #编码格式
      settings:
        number_format: '0.##'   #数字格式化，无小数点 
    datasource:
        name: test
        url: jdbc:mysql://118.31.59.56:3306/itms
        username: lister
        password: lister 
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20 
        logSlowSql: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lister.itms.dao.entity
# Mybatis 分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql  
# 日志
logging:
  file:
  path:
  level: 
#    org.springframework: DEBUG
    com.lister.itms: DEBUG
    # Mybatis SQL Log    
    com.lister.itms.dao.mapper: DEBUG    
